zookeeper:
  servers: zookeeper-zookeeper-dev004-whdx.qiyi.virtual:2181
  path: /frontweb_proxy_test/zkconfig/config
  connectTimeout: 30000
  connectionPath: /frontweb_proxy_test/zkconfig/connection
  scheme: digest
  username: frontweb_proxy_test
  password: frontweb_proxy_test
spring:
  freemarker:
    settings:
      dateFormat: yyyy-MM-dd
      timeFormat: HH:mm:ss
      datetimeFormat: yyyy-MM-dd HH:mm:ss
    request-context-attribute: request
