zookeeper:
  servers: 10.110.28.204:2181
  path: /zkconfig/config
  connectTimeout: 30000
  connectionPath: /zkconfig/connection
  scheme: digest
  username: zkconfig
  password: zkconfig
zkconfig:
  typeList:
    - properties
    - json
    - yaml
  contentDefault:
    properties: "#java properties format, such as:\n#key=value"
    json: "{\n\t\"key\":\"value\"\n}"
    yaml: "# yaml format config, such as: \n#root:\n#  key: value"
  adminUserName: shushanfx
  adminEmail: shushanfx@gmail.com
spring:
  freemarker:
    settings:
      dateFormat: yyyy-MM-dd
      timeFormat: HH:mm:ss
      datetimeFormat: yyyy-MM-dd HH:mm:ss
    request-context-attribute: request